<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__r_address1.phone</name>
   <tag></tag>
   <elementGuidId>974a5cb1-f097-4fff-802b-170b279e875c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1baa7f0-608b-4bd9-b11d-15c7c874b5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>1e18d502-e56a-4d4f-9ee7-0a34be8a6bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2f57090-2f59-4161-a788-4f9e20445269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>หมายเลขโทรศัพท์ (ไม่บังคับใส่)</value>
      <webElementGuid>0dcb6d75-17be-41d0-8894-73f882273ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>r_address/1.phone</value>
      <webElementGuid>40076a2a-2674-4b32-8ec4-fd9e12da7c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mandate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f89b5a9e-a7a0-49fc-96e9-aeeab18658fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile&quot;)</value>
      <webElementGuid>d05f6505-881a-452d-a08a-3c85ddac8135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile']</value>
      <webElementGuid>f6710f41-829c-4b49-b9b7-9a38f9b51848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupform']/div/div[4]/div/input</value>
      <webElementGuid>6f93b55f-144e-4bde-8d05-15afd0bccbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>38f0e61f-7e72-4775-a0d6-830eba6f3cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mobile' and @type = 'text' and @placeholder = 'หมายเลขโทรศัพท์ (ไม่บังคับใส่)' and @name = 'r_address/1.phone']</value>
      <webElementGuid>6f1f63b8-b6d1-4608-a63c-79e0500e644d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
