<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__signupbtn</name>
   <tag></tag>
   <elementGuidId>7dba4873-af82-4c88-b44a-4d459767e9ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signupbtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signupbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e068d20-cb5f-4cbf-b075-371d2aff42df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signupbtn</value>
      <webElementGuid>d1da74bf-dafd-4dc6-b05a-0c74f4e18071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value> return zSignupPrevent();</value>
      <webElementGuid>7e1a59af-e842-43bb-bbed-4fdc3b7cb060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signupbtn</value>
      <webElementGuid>26e11f24-b0af-42bc-a105-c78268a1e46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>495ebf53-9ef6-424f-b559-3ea3e9eb819c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ลงทะเบียนฟรี</value>
      <webElementGuid>296c533d-9bf6-48fc-a01b-58b417c53dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupbtn&quot;)</value>
      <webElementGuid>8ead9987-446d-417c-a85c-780675acfea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signupbtn']</value>
      <webElementGuid>af135888-509f-4dfa-a003-7d8bdee3980f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupform']/div/div[8]/div[3]/input</value>
      <webElementGuid>aff598d1-4a80-4ea0-9809-20736bc60ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>db56ad7a-54b8-4bca-a8f4-5f3412e68b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signupbtn' and @type = 'submit']</value>
      <webElementGuid>0edf293d-c018-4b8e-9bd4-140c55d1f761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
