<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__r_account.account_name</name>
   <tag></tag>
   <elementGuidId>9c1eefd1-0fd1-4a5d-b53b-fd1ead243afd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='portalcompanyname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#portalcompanyname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70ac43ce-c6dd-40c4-b4f2-a9c71fb07954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f97a4a66-182c-4e4f-9afd-b569aa3c0ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>portalcompanyname</value>
      <webElementGuid>0250e621-8d28-4679-85cd-d86a573a7d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ชื่อบริษัท
 *</value>
      <webElementGuid>0b70f3ce-ee4d-4826-aef6-09deda889e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>dispportalName()</value>
      <webElementGuid>e31bc449-b813-401d-913d-1980ba1d38ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sgname sgnusrname p_name</value>
      <webElementGuid>a4ace456-67bd-499f-9d1b-e8bc96195baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>r_account.account_name</value>
      <webElementGuid>820658da-4bc7-432f-9c7d-43108bb9f24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$('#x_portal').trigger('blur');</value>
      <webElementGuid>b417ced6-312f-4d09-98e8-ee100882f986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portalcompanyname&quot;)</value>
      <webElementGuid>fe09233f-a04a-43ca-b4a3-1be2ec7c9782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='portalcompanyname']</value>
      <webElementGuid>2f2f26f9-1bab-4dc6-b83f-48edeaa06f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupform']/div/div/div/input</value>
      <webElementGuid>bdbce57b-20b2-4d75-b969-11d35f0a079f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>085db681-88e5-4434-a4f2-9dfbee92e1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'portalcompanyname' and @placeholder = 'ชื่อบริษัท
 *' and @name = 'r_account.account_name']</value>
      <webElementGuid>9aeb94a6-396e-43b3-9f2e-ea3eb7b82d03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
