<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>89aed605-85fa-47b1-9fa3-095a737b1a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='signup-termservice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signup-termservice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15217d7f-f9a0-42ca-aabf-67e9eed19646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>a1aa40d0-94a9-4cc4-8fdb-611117bea4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup-termservice</value>
      <webElementGuid>52e4c23a-f248-4068-874a-48a6b634c219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>d1668f15-5702-4668-baa4-22e534d8093c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup-termservice&quot;)</value>
      <webElementGuid>b1c77b63-b7ec-4d8c-8eda-dbc75f79c5f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='signup-termservice']</value>
      <webElementGuid>2b53e81e-65c1-4931-88ef-ba7c215a558e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupform']/div/div[8]/div[2]/label/span</value>
      <webElementGuid>81e23444-f4c2-42f1-8ef9-f351337d437a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US'])[1]/following::span[4]</value>
      <webElementGuid>f3bae35a-8e78-4d5c-940e-607d9e557ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ข้อกำหนดในการให้บริการ'])[1]/preceding::span[1]</value>
      <webElementGuid>4529c83f-e879-48ef-82fb-c3905b04b331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นโยบายความเป็นส่วนตัว'])[1]/preceding::span[1]</value>
      <webElementGuid>059b0b0f-3124-4559-9dbf-7087ee6740e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span</value>
      <webElementGuid>524c5147-38cb-4ef2-b3ea-37e2948b6096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'signup-termservice' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>026d52dd-be84-491a-a181-4cbb9d98ae0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
